=== chajr/bluetree20/BLUE_FRAMEWORK/cfg/dtd/tree.dtd
<!ELEMENT root (lib*, mod*, css*, js*, page*)>
	<!ATTLIST root options (1|0) #REQUIRED>				<!--czy caly system jest wlaczony-->
	<!ELEMENT lib (#PCDATA)>							<!--element dla glownych bibliotek (zawsze wymaganych)-->
		<!ATTLIST lib on (1|0) #REQUIRED>				<!--czy biblioteka ma byc wlaczona/zaladowana-->
	<!ELEMENT mod (#PCDATA)>							<!--element dla glownych modow (zawsze wymaganych)-->
		<!ATTLIST mod on (1|0) #REQUIRED>				<!--czy mod ma byc wlaczony-->
		<!ATTLIST mod param CDATA #IMPLIED>				<!--lista dodatkowych, ewentualnych parametrow dla modu-->
		<!ATTLIST mod exec CDATA #IMPLIED>				<!--okresla nazwe pliku exec z ktorego ma startowac mod, jesli inny-->
		<!ATTLIST mod block CDATA #IMPLIED>				<!--nazwa bloku do ktorego zostanie zaladowany modul, kolejnosc == pozycja-->
	<!ELEMENT css (#PCDATA)>							<!--nazwy plikow css lub adresy url dla zewnetrznych css-->
		<!ATTLIST css media CDATA #IMPLIED>				<!--opcjonalnie atrybut media-->
		<!ATTLIST css external (0|1) #IMPLIED>			<!--opcjonalnie czy css zewnetrzny (domyslnie wewnetrzny)-->
	<!ELEMENT js (#PCDATA)>								<!--adresy url dla zewnetrznych js-->
		<!ATTLIST js external (0|1) #IMPLIED>			<!--opcjonalnie czy css zewnetrzny (domyslnie wewnetrzny)-->
	<!ELEMENT page (menu*, sub*, lib*, mod*, css*, js*)><!--lista stron glownych wraz z ich podstronami, bibliotekami, modulami i zewnetrznymi plikami-->
		<!ATTLIST page id ID #REQUIRED>					<!--id z nazwa strony (pierwszy partametr w GET)-->
		<!ATTLIST page layout CDATA #REQUIRED>			<!--nazwa szkieletu html do zaladowania, jesli 0 nie laduje-->
		<!ATTLIST page external CDATA #IMPLIED>			<!--jesli ma zaladowac zewnetrzny plik xml, np dla admina-->
		<!ATTLIST page name CDATA #REQUIRED>			<!--nazwa strony (dla nawigacji/tytulow)-->
		<!ATTLIST page options CDATA #REQUIRED>			<!--opcje strony binarnie (wlaczony, widoczny w drzewie, widoczny w menu, widoczny w breadcrumbs)-->
		<!ATTLIST page redirect CDATA #IMPLIED>			<!--opcjonalny okreslajacy id strony do ktorej ma wykonac przekierowanie-->
		<!ATTLIST page startDate CDATA #IMPLIED>		<!--data od ktorej ma zostac wyswietlona strona (format unixowy)-->
		<!ATTLIST page endDate CDATA #IMPLIED>			<!--data do ktorej strona ma byc wyswietlana (format unixowy)-->
		<!ATTLIST page changefreq CDATA #IMPLIED>		<!--czestotliwosc zmian na stronie (sitemap)-->
		<!ATTLIST page priority CDATA #IMPLIED>			<!--priorytet strony-->
	<!ELEMENT sub (menu*, sub*, lib*, mod*, css*, js*)>	<!--opcjonalny, wielokrotny element podstrony)-->
		<!ATTLIST sub id CDATA #REQUIRED>				<!--id z nazwa strony (pierwszy partametr w GET)-->
		<!ATTLIST sub layout CDATA #REQUIRED>			<!--nazwa szkieletu html do zaladowania, jesli 0 nie laduje-->
		<!ATTLIST sub name CDATA #REQUIRED>				<!--nazwa strony (dla nawigacji/tytulow)-->
		<!ATTLIST sub external CDATA #IMPLIED>			<!--jesli ma zaladowac zewnetrzny plik xml, np dla admina-->
		<!ATTLIST sub options CDATA #REQUIRED>			<!--opcje strony binarnie (wlaczony, ukryty w drzewie, widoczny w menu, widoczny w breadcrumbs, dziedziczenie)-->
		<!ATTLIST sub redirect CDATA #IMPLIED>			<!--opcjonalny okreslajacy id strony do ktorej ma wykonac przekierowanie-->
		<!ATTLIST sub startDate CDATA #IMPLIED>			<!--data od ktorej ma zostac wyswietlona strona (format unixowy)-->
		<!ATTLIST sub endDate CDATA #IMPLIED>			<!--data do ktorej strona ma byc wyswietlana (format unixowy)-->
		<!ATTLIST sub changefreq CDATA #IMPLIED>		<!--czestotliwosc zmian na stronie (sitemap)-->
		<!ATTLIST sub priority CDATA #IMPLIED>			<!--priorytet strony-->
	<!ELEMENT menu (#PCDATA)>							<!--lista indentyfikatorow menu z ktorymi ma byc powiazana strona/podstrona (main okresla glone menu strony)-->

=== chajr/bluetree20/BLUE_FRAMEWORK/cfg/tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
* Framework page structure configuration
*
* @category    BlueFramework
* @package     BlueFramework Core
* @author      MichaÅ‚ Adamiak    <chajr@bluetree.pl>
* @copyright   chajr/bluetree
* @version     1.5.0
*/
-->
<!DOCTYPE root SYSTEM 'dtd/tree.dtd'>
<root options="1">
    <lib on="1">valid</lib>
    <lib on="0">jakas_biblioteka</lib>
    <lib on="1">user</lib>
    <css>bootstrap_dark</css>
    <css>elusive-webfont</css>
    <css>elusive-webfont-ie7</css>
    <css>base</css>
    <js external="1">//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js</js>
    <js>js1</js>
    <js>bootstrap</js>

    <page id="index" name="{;lang;core;main_page;}" layout="index" options="1111" changefreq="always" priority="0.8">
        <lib on="1">db/sql_abstract,mysql_connection</lib>
        <lib on="1">db/mysql</lib>
        <lib on="1">time</lib>
        <lib on="1">image/image</lib>
        <lib on="1">forms</lib>
        <mod on="1" param="jakis::inny">modul1</mod>
        <mod on="1" block="blok_testowy">mod2</mod>
        <mod on="1" block="blok_testowy">mod3</mod>
        <mod on="1" param="breadcrumbs">main</mod>
        <css external="0">css2</css>
        <css external="0">css3</css>
        <css external="0" media="print">as</css>
        <css>styles</css>
        <js>js2</js>
    </page>

    <page id="examples" name="{;lang;core;example_title;}" layout="examples/examples" options="1111">
        <sub id="example_generate" name="{;lang;core;generate_content;}" layout="examples/example" options="11111">
            <mod on="1" block="examples">example_generate</mod>
        </sub>
        <sub id="example_messages" name="{;lang;core;generate_content;}" layout="examples/example" options="11111">
            <mod on="1" block="examples">example_messages</mod>
        </sub>
        <sub id="example_layouts" name="{;lang;core;generate_content;}" layout="examples/example" options="11111">
            <mod on="1" block="examples">example_layout</mod>
        </sub>
        <mod on="1" param="breadcrumbs">main</mod>
        <css>styles</css>
        <css>shCore</css>
        <css>shThemeDefault</css>
        <js>XRegExp</js>
        <js>shCore</js>
        <js>shBrushPhp</js>
        <js>shBrushXml</js>
        <js>examples</js>
    </page>

    <page id="strona2" name="Page 2" layout="strona2" options="1111" changefreq="always" priority="0.8">
        <sub id="podstrona1" name="Subpage 1" layout="strona2" options="11111" changefreq="always" priority="0.8">
            <!--<lib on="1">files</lib>-->
            <!--<mod on="1">mod4</mod>-->
            <css>css4</css>
            <js>js4</js>
        </sub>

        <sub id="podstrona2" name="Subpage 2" layout="podstrona2" options="11110">
            <lib on="1">disc</lib>
            <mod on="1">mod5</mod>
            <css>css5</css>
            <js>js5</js>
        </sub>

        <lib on="1">db/abstractSql</lib>
        <lib on="1">db/mysql</lib>
        <lib on="1">image</lib>
        <lib on="1">time</lib>
        <lib on="1">forms</lib>
        <mod on="1" param="jakis">modul1</mod>
        <mod on="1" block="blok_testowy">mod2</mod>
        <css external="0">css2</css>
        <css external="0">css3</css>
    </page>

    <page id="strona3" name="Page 3" layout="strona3" options="1111">
        <sub id="podstrona3" name="Subpage 3" layout="podstrona3" options="11110">
            <sub id="podstrona4" name="Subpage 4" layout="podstrona4" options="11110">
                <mod on="1">map</mod>
            </sub>
            <lib on="1">db/mysql</lib>
            <lib on="1">files</lib>
            <mod on="1">mod6</mod>
        </sub>

        <lib on="1">db/mysql</lib>
        <mod on="1" param="jakis">modul1</mod>
        <mod on="1">mod3</mod>
        <mod on="1">modd</mod>
    </page>

    <page id="commit" name="Commit creator" layout="commit" options="1111">
        <sub id="generate" name="Commit creator" layout="commit" options="11111">
            <mod on="1" param="generate">commit</mod>
        </sub>
        <mod on="1">commit</mod>
    </page>

    <page id="ajax_test" layout="ajax" name="Ajax" options="1000">
        <mod on="1">mod_ajax</mod>
    </page>

    <page id="error404" name="error404" layout="404" options="1001">
        <css>error_css</css>
        <js>error_js</js>
    </page>

    <page id="sitemap" name="sitemap" layout="empty" options="1001">
        <mod on="1" param="sitemap">main</mod>
    </page>

    <page id="forum" name="forum" layout="empty" options="1001"
          redirect="http://wataha.at/forum"
    />
</root>
